name: Issue Labeler

on:
  issues:
    types: [opened, edited, reopened]

jobs:
  issue-labeler:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - name: Apply labels to issues
        uses: actions/github-script@v8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const config = {
              "bug": [/bug/i, /error/i, /crash/i],
              "feature": [/feature/i, /enhancement/i],
              "docs": [/docs?/i, /documentation/i],
            };

            const title = context.payload.issue.title;
            const body = context.payload.issue.body || "";
            let labelsToAdd = [];

            for (const [label, patterns] of Object.entries(config)) {
              if (patterns.some(re => re.test(title) || re.test(body))) {
                labelsToAdd.push(label);
              }
            }

            if (labelsToAdd.length > 0) {
              await github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: labelsToAdd
              });
            }
