name: MSVC-CI
on:
  push:
    branches: [ __main__ ]
  pull_request:
    branches: [ __main__ ]
  workflow_dispatch:

permissions:
  contents: read
  packages: read

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Configure and Build
        run: |
          mkdir build
          cd build
          cmake -A Win32 ..
          cmake --build . --config Debug
          cmake --build . --config Release
      - name: Run Tests (Debug)
        run: cmake --build build --config Debug --target RUN_TESTS || cmake --build build --config Debug --target check
      - name: Run Tests (Release)
        run: cmake --build build --config Release --target RUN_TESTS || cmake --build build --config Release --target check
      - name: Upload Release Executables
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: pycdc-release
          path: build\Release\*.exe
          
